from tkinter import * 
import tkinter
import pymysql
from tkinter import messagebox
def customerInsert():
    t=tkinter.Tk()
    t.geometry('650x650')
    t.title('Customer Entry')
    def saveData():
        db=pymysql.connect(host='localhost',
                           user='root',
                           password='Vkumar@1234',
                           db='StockManagement'
                           )
        cur=db.cursor()
        p=a.get()
        q=b.get()
        r=c.get()
        s=d.get()
        if len(p)==0 or len(q)==0 or len(r)==0 or len(s)==0:
            messagebox.showerror('Error','CANNOT BLANK..')
        else:
            st="insert into  customer values('%s','%s','%s','%s')"%(p,q,r,s)
            cur.execute(st)
            db.commit()
            db.close()
            messagebox.showinfo('saved')
            a.delete(0,100)
            b.delete(0,100)
            c.delete(0,100) 
            d.delete(0,100)   
    l1=Label(t,text='Customer ID',bg='sky blue',font='bold ')  
    l1.place(x=30,y=30) 
    l2=Label(t,text='Customer Name',bg='sky blue',font='bold')  
    l2.place(x=30,y=60) 
    l3=Label(t,text='Email Address',bg='sky blue',font='bold')  
    l3.place(x=30,y=90) 
    l4=Label(t,text='Phone Number',bg='sky blue',font='bold')  
    l4.place(x=30,y=120) 
    a=Entry(t,width=20,font='bold')
    a.place(x=400,y=30)
    b=Entry(t,width=20,font='bold')
    b.place(x=400,y=60)
    c=Entry(t,width=20,font='bold')
    c.place(x=400,y=90)
    d=Entry(t,width=20,font='bold')
    d.place(x=400,y=120)
    f1=Frame(t,bg='grey',borderwidth=3)
    bt=Button(f1,text='Save',padx=15,pady=3,command=saveData,bg='light grey',font='bold')
    bt.pack()
    f1.place(x=400,y=210)
    t.config(bg='sky blue')
    t.mainloop()
def itemcategoryInsert():
    t=tkinter.Tk()
    t.geometry('650x650')
    t.title('Item Category Entry')
    def saveData():
        db=pymysql.connect(host='localhost',
                           user='root',
                          password='Vkumar@1234',
                          db='StockManagement'
                           )
        cur=db.cursor()
        p=a.get()
        q=b.get()
        r=c.get()
        if len(p)==0 or len(q)==0 or len(r)==0:
            messagebox.showerror('Error','CANNOT BLANK..')
        else:
       
            st="insert into  itemcategory values('%s','%s','%s')"%(p,q,r)
            cur.execute(st)
            db.commit()
            db.close()
            messagebox.showinfo('saved')
            a.delete(0,100)
            b.delete(0,100)
            c.delete(0,100)
        
    l1=Label(t,text='Item Category ID',bg='sky blue',font='bold ')  
    l1.place(x=30,y=30) 
    l2=Label(t,text='Category Name',bg='sky blue',font='bold')  
    l2.place(x=30,y=60) 
    l3=Label(t,text='Description',bg='sky blue',font='bold')  
    l3.place(x=30,y=90) 
    a=Entry(t,width=20)
    a.place(x=400,y=30)
    b=Entry(t,width=20)
    b.place(x=400,y=60)
    c=Entry(t,width=20)
    c.place(x=400,y=90)
    f=Frame(t,bg='grey',borderwidth=3)
    bt=Button(f,text='Save',padx=15,pady=3,command=saveData,bg='light grey')
    bt.pack()
    f.place(x=400,y=150)
    t.config(bg='sky blue')
    t.mainloop()
    
def itemsInsert():
    t=tkinter.Tk()
    t.geometry('650x650')
    t.title('Item Entry')
    def saveData():
        import pymysql
        from tkinter import messagebox
        db=pymysql.connect(host='localhost',
                           user='root',
                           password='Vkumar@1234',
                           db='stockmanagement'
                           )
        cur=db.cursor()
        p=a.get()
        q=b.get()
        r=c.get()
        s=(d.get())
        t=(e.get())
        u=(f.get())
        if len(p)==0 or len(q)==0 or len(r)==0 or len(s)==0 or len(t)==0 or len(u)==0:
            messagebox.showerror('Error','CANNOT BLANK..')
        else:
            st="insert into  items values('%s','%s','%s',%s,%s,%s)"%(p,q,r,s,t,u)
            cur.execute(st)
            db.commit()
            db.close()
            messagebox.showinfo('saved')
            a.delete(0,100)
            b.delete(0,100)
            c.delete(0,100) 
            d.delete(0,100)  
            e.delete(0,100)
            f.delete(0,100)
    l1=Label(t,text='Item ID',bg='sky blue',font='bold ')  
    l1.place(x=30,y=30) 
    l2=Label(t,text='Item Category ID',bg='sky blue',font='bold')  
    l2.place(x=30,y=60) 
    l3=Label(t,text='Item Name',bg='sky blue',font='bold')  
    l3.place(x=30,y=90) 
    l4=Label(t,text='Price Per Unit',bg='sky blue',font='bold')  
    l4.place(x=30,y=120) 
    l5=Label(t,text='Open Quantity',bg='sky blue',font='bold')  
    l5.place(x=30,y=150) 
    l6=Label(t,text='Current Quantity',bg='sky blue',font='bold')  
    l6.place(x=30,y=180) 
    a=Entry(t,width=20,font='bold')
    a.place(x=400,y=30)
    b=Entry(t,width=20,font='bold')
    b.place(x=400,y=60)
    c=Entry(t,width=20,font='bold')
    c.place(x=400,y=90)
    d=Entry(t,width=20,font='bold')
    d.place(x=400,y=120)
    e=Entry(t,width=20,font='bold')
    e.place(x=400,y=150)
    f=Entry(t,width=20,font='bold')
    f.place(x=400,y=180)
    bt=Button(t,text='Save',command=saveData,bg='light grey',font='bold')
    bt.place(x=400,y=210)
    t.config(bg='sky blue')
    t.mainloop()


    
def ordersInsert(): 
    t=tkinter.Tk()           
    t.geometry('650x650')
    t.title('Order Entry')
    def saveData():
        db=pymysql.connect(host='localhost',
                           user='root',
                          password='Vkumar@1234',
                          db='StockManagement'
                           )
        cur=db.cursor()
        p=a.get()
        q=b.get()
        r=c.get()
        s=d.get()
        t=e.get()
        u=f.get()
        if len(p)==0 or len(q)==0 or len(r)==0 or len(s)==0 or len(t)==0 or len(u)==0:
            messagebox.showerror('Error','CANNOT BLANK..')
        else:
            st="insert into  orders values('%s','%s','%s','%s','%s','%s')"%(p,q,r,s,t,u)
            cur.execute(st)
            db.commit()
            db.close()
            messagebox.showinfo('saved')
            a.delete(0,100)
            b.delete(0,100)
            c.delete(0,100) 
            d.delete(0,100)  
            e.delete(0,100)  
            f.delete(0,100)
    l1=Label(t,text='Order ID',bg='sky blue',font='bold ')  
    l1.place(x=30,y=30) 
    l2=Label(t,text='Customer ID',bg='sky blue',font='bold')  
    l2.place(x=30,y=60) 
    l3=Label(t,text='Order Date',bg='sky blue',font='bold')  
    l3.place(x=30,y=90) 
    l4=Label(t,text='Item ID',bg='sky blue',font='bold')  
    l4.place(x=30,y=120) 
    l5=Label(t,text='Item Category ID',bg='sky blue',font='bold')  
    l5.place(x=30,y=150) 
    l6=Label(t,text='Quantity',bg='sky blue',font='bold')  
    l6.place(x=30,y=180) 
    a=Entry(t,width=20,font='bold')
    a.place(x=400,y=30)
    b=Entry(t,width=20,font='bold')
    b.place(x=400,y=60)
    c=Entry(t,width=20,font='bold')
    c.place(x=400,y=90)
    d=Entry(t,width=20,font='bold')
    d.place(x=400,y=120)
    e=Entry(t,width=20,font='bold')
    e.place(x=400,y=150)
    f=Entry(t,width=20,font='bold')
    f.place(x=400,y=180)
    f1=Frame(t,bg='grey',borderwidth=3)
    bt=Button(f1,text='Save',padx=15,pady=3,command=saveData,bg='light grey',font='bold')
    bt.pack()
    f1.place(x=400,y=240)
    t.config(bg='sky blue')
    t.mainloop()

def billsInsert():
    t=tkinter.Tk()
    t.geometry('650x650')
    t.title('Bill Entry')
    def saveData():
        db=pymysql.connect(host='localhost',
                           user='root',
                           password='Vkumar@1234',
                           db='StockManagement'
                           )
        cur=db.cursor()
        p=a.get()
        q=b.get()
        r=c.get()
        s=(d.get())
        t=(e.get())
        u=f.get()
        v=(g.get())
        if len(p)==0 or len(q)==0 or len(r)==0 or len(s)==0 or len(t)==0 or len(u)==0 or len(v)==0:
            messagebox.showerror('Error','CANNOT BLANK..')
        else:
            st="insert into  bills values('%s','%s','%s',%s,%s,'%s',%s)"%(p,q,r,s,t,u,v)
            cur.execute(st)
            db.commit()
            db.close()
            messagebox.showinfo('saved')
            a.delete(0,100)
            b.delete(0,100)
            c.delete(0,100) 
            d.delete(0,100)  
            e.delete(0,100)  
            f.delete(0,100)
            g.delete(0,100)
    l1=Label(t,text='Bill ID',bg='sky blue',font='bold ')  
    l1.place(x=30,y=30) 
    l2=Label(t,text='Order ID',bg='sky blue',font='bold')  
    l2.place(x=30,y=60) 
    l3=Label(t,text='Customer ID',bg='sky blue',font='bold')  
    l3.place(x=30,y=90) 
    l4=Label(t,text='Quantity',bg='sky blue',font='bold')  
    l4.place(x=30,y=120) 
    l5=Label(t,text='Price',bg='sky blue',font='bold')  
    l5.place(x=30,y=150) 
    l6=Label(t,text='GST',bg='sky blue',font='bold')  
    l6.place(x=30,y=180)
    l7=Label(t,text='Total Bill',bg='sky blue',font='bold')  
    l7.place(x=30,y=210) 
    a=Entry(t,width=20,font='bold')
    a.place(x=400,y=30)
    b=Entry(t,width=20,font='bold')
    b.place(x=400,y=60)
    c=Entry(t,width=20,font='bold')
    c.place(x=400,y=90)
    d=Entry(t,width=20,font='bold')
    d.place(x=400,y=120)
    e=Entry(t,width=20,font='bold')
    e.place(x=400,y=150)
    f=Entry(t,width=20,font='bold')
    f.place(x=400,y=180)
    g=Entry(t,width=20,font='bold')
    g.place(x=400,y=210)
    f1=Frame(t,bg='grey',borderwidth=3)
    bt=Button(f1,text='Save',padx=15,pady=3,command=saveData,bg='light grey',font='bold')
    bt.pack()
    f1.place(x=400,y=240)
    t.config(bg='sky blue')
    t.mainloop()
    
def stockInsert():
    t=tkinter.Tk()
    t.geometry('650x650')
    t.title('Stock Entry')
    def saveData():
        db=pymysql.connect(host='localhost',
                           user='root',
                          password='Vkumar@1234',
                          db='StockManagement'
                           )
        cur=db.cursor()
        p=a.get()
        q=b.get()
        r=c.get()
        s=d.get()
        t=(e.get())
        if len(p)==0 or len(q)==0 or len(r)==0 or len(s)==0 or len(t)==0:
            messagebox.showerror('Error','CANNOT BLANK..')
        else:
            st="insert into  stock values('%s','%s','%s','%s',%s)"%(p,q,r,s,t)
            cur.execute(st)
            db.commit()
            db.close()
            messagebox.showinfo('saved')
            a.delete(0,100)
            b.delete(0,100)
            c.delete(0,100) 
            d.delete(0,100)  
            e.delete(0,100)  
    l1=Label(t,text='Stock ID',bg='sky blue',font='bold ')  
    l1.place(x=30,y=30) 
    l2=Label(t,text='Item ID',bg='sky blue',font='bold')  
    l2.place(x=30,y=60) 
    l3=Label(t,text='Item Category ID',bg='sky blue',font='bold')  
    l3.place(x=30,y=90) 
    l4=Label(t,text='Date In',bg='sky blue',font='bold')  
    l4.place(x=30,y=120) 
    l5=Label(t,text='Quantity',bg='sky blue',font='bold')  
    l5.place(x=30,y=150) 
    a=Entry(t,width=20,font='bold')
    a.place(x=400,y=30)
    b=Entry(t,width=20,font='bold')
    b.place(x=400,y=60)
    c=Entry(t,width=20,font='bold')
    c.place(x=400,y=90)
    d=Entry(t,width=20,font='bold')
    d.place(x=400,y=120)
    e=Entry(t,width=20,font='bold')
    e.place(x=400,y=150)
    f1=Frame(t,bg='grey',borderwidth=3)
    bt=Button(f1,text='Save',padx=15,pady=3,command=saveData,bg='light grey',font='bold')
    bt.pack()
    f1.place(x=400,y=180)
    t.config(bg='sky blue')
    t.mainloop()

def itemcategoryFind():
    t=tkinter.Tk()
    t.geometry('650x650')
    t.title('find data from itemcategory')
    def findData():
        db=pymysql.connect(host='localhost',user='root',password='Vkumar@1234',
        db='StockManagement')
        cur=db.cursor()
        p=(a.get())
        if len(p)==0:
            messagebox.showerror('Error','CANNOT FIND !')
        else:
            st="Select  CatName, description from itemcategory where itemcatid='%s'"%p
            cur.execute(st)
            data=cur.fetchone()
            b.insert(0,data[0])
            c.insert(0,data[1])
            db.commit()
            db.close()
    l1=Label(t,text='Item Category ID',bg='sky blue')  
    l1.place(x=30,y=30) 
    l1=Label(t,text='Categoty Name',bg='sky blue')  
    l1.place(x=30,y=60) 
    l1=Label(t,text='Description',bg='sky blue')  
    l1.place(x=30,y=90)  
    a=Entry(t,width=20)
    a.place(x=400,y=30)
    b=Entry(t,width=20)
    b.place(x=400,y=60)
    c=Entry(t,width=20)
    c.place(x=400,y=90)
    f=Frame(t,bg='grey',borderwidth=3)
    bt=Button(f,text='Find',padx=15,pady=3,command=findData,bg='light grey')
    bt.pack()
    f.place(x=400,y=120)
    t.config(bg='sky blue')
    t.mainloop()

def itemsFind():
    t=tkinter.Tk()
    t.geometry('650x650')
    t.title('find data from items')
    def findData():
        db=pymysql.connect(host='localhost',user='root',password='Vkumar@1234',
        db='StockManagement')
        cur=db.cursor()
        p=(a.get())
        if len(p)==0:
            messagebox.showerror('Error','CANNOT FIND !')
        else:
            st="Select  itemcatid, iname, priceperunit, openqty, currentqty from items where itemid='%s'"%(p)
            cur.execute(st)
            data=cur.fetchone()
            b.insert(0,data[0])
            c.insert(0,data[1])
            d.insert(0,data[2])
            e.insert(0,data[3])
            f1.insert(0,data[4])
            db.commit()
            db.close()
    l1=Label(t,text='Item ID',bg='sky blue')  
    l1.place(x=30,y=30) 
    l2=Label(t,text='Item Category ID',bg='sky blue')  
    l2.place(x=30,y=60) 
    l3=Label(t,text='Item Name',bg='sky blue')  
    l3.place(x=30,y=90)
    l4=Label(t,text='Price Per Unit',bg='sky blue')  
    l4.place(x=30,y=120)
    l5=Label(t,text='Open Quantity',bg='sky blue')  
    l5.place(x=30,y=150)
    l6=Label(t,text='Current Quantity',bg='sky blue')  
    l6.place(x=30,y=180)  
    a=Entry(t,width=20)
    a.place(x=400,y=30)
    b=Entry(t,width=20)
    b.place(x=400,y=60)
    c=Entry(t,width=20)
    c.place(x=400,y=90)
    d=Entry(t,width=20)
    d.place(x=400,y=120)
    e=Entry(t,width=20)
    e.place(x=400,y=150)
    f1=Entry(t,width=20)
    f1.place(x=400,y=180)
    f=Frame(t,bg='grey',borderwidth=3)
    bt=Button(f,text='Find',padx=15,pady=3,command=findData,bg='light grey')
    bt.pack()
    f.place(x=400,y=210)
    t.config(bg='sky blue')
    t.mainloop()
    
def customerFind():
    t=tkinter.Tk()
    t.geometry('650x650')
    t.title('find data from customer')
    def finddata():
        db=pymysql.connect(host='localhost',
            user='root',password='Vkumar@1234',db='StockManagement')
        cur=db.cursor()
        p=(a.get())
        #placeholders %s string,%d int
        if len(p)==0:
            messagebox.showerror('Error','CANNOT FIND !')
        else:
            st="select CName,Email,PhoneNo from customer where CustID='%s'"%(p)
            cur.execute(st)
            data=cur.fetchone()
            b.insert(0,data[0])
            c.insert(0,data[1])
            d.insert(0,data[2])
            #save
            db.close()
    l1=Label(t,text='CustID',bg='sky blue',font='bold ') 
    l1.place(x=100,y=50)   
    a=Entry(t,width=20)
    a.place(x=200,y=50)
    btf=Button(t,text='Find',command=finddata)
    btf.place(x=400,y=50)
    l2=Label(t,text='CName',bg='sky blue',font='bold ')
    l2.place(x=100,y=100)
    b=Entry(t,width=20)
    b.place(x=200,y=100)
    l3=Label(t,text='Email',bg='sky blue',font='bold ')
    l3.place(x=100,y=150)
    c=Entry(t,width=20)
    c.place(x=200,y=150)
    l4=Label(t,text='PhoneNo',bg='sky blue',font='bold ')
    l4.place(x=100,y=200)
    d=Entry(t,width=20)
    d.place(x=200,y=200)
    t.config(bg='sky blue')
    t.mainloop()
    
def ordersFind():
   t=tkinter.Tk()
   t.geometry('650x650')
   t.title('find data from orders')
   def finddata():
       db=pymysql.connect(host='localhost',
           user='root',password='Vkumar@1234',db='StockManagement')
       cur=db.cursor()
       p=(a.get())
       #placeholders %s string,%d int
       if len(p)==0:
            messagebox.showerror('Error','CANNOT FIND !')
       else:
           st="select CustId,OrdDate,ItemId,ItemCatID,Qty from orders where OrderID='%s'"%(p)
           cur.execute(st)
           data=cur.fetchone()
           b.insert(0,data[0])
           c.insert(0,data[1])
           d.insert(0,data[2])
           e.insert(0,data[3])
           f.insert(0,data[4])
           #save
           db.close()
   l1=Label(t,text='OrderID',bg='sky blue',font='bold ') 
   l1.place(x=100,y=50)   
   a=Entry(t,width=20)
   a.place(x=200,y=50)
   btf=Button(t,text='Find',command=finddata)
   btf.place(x=400,y=50)
   l2=Label(t,text='CustId',bg='sky blue',font='bold ')
   l2.place(x=100,y=100)
   b=Entry(t,width=20)
   b.place(x=200,y=100)
   l3=Label(t,text='OrdDate',bg='sky blue',font='bold ')
   l3.place(x=100,y=150)
   c=Entry(t,width=20)
   c.place(x=200,y=150)
   l4=Label(t,text='ItemId',bg='sky blue',font='bold ') 
   l4.place(x=100,y=200)   
   d=Entry(t,width=20)
   d.place(x=200,y=200)
   l5=Label(t,text='ItemCatID',bg='sky blue',font='bold ') 
   l5.place(x=100,y=250)   
   e=Entry(t,width=20)
   e.place(x=200,y=250)
   l6=Label(t,text='Qty',bg='sky blue',font='bold ') 
   l6.place(x=100,y=300)   
   f=Entry(t,width=20)
   f.place(x=200,y=300)
   t.config(bg='sky blue')

   t.mainloop()

def billsFind():
   t=tkinter.Tk()
   t.geometry('650x650')
   t.title('find data from bills')
   def finddata():
       db=pymysql.connect(host='localhost',
           user='root',password='Vkumar@1234',db='StockManagement')
       cur=db.cursor()
       p=(a.get())
       #placeholders %s string,%d int
       if len(p)==0:
            messagebox.showerror('Error','CANNOT FIND !')
       else:
           st="select OrderId,CustID,Qty,Price,GST,TotalBill from bills where BillID='%s'"%(p)
           cur.execute(st)
           data=cur.fetchone()
           b.insert(0,data[0])
           c.insert(0,data[1])
           d.insert(0,data[2])
           e.insert(0,data[3])
           f.insert(0,data[4])
           g.insert(0,data[5])
           #save
           db.close()
   l1=Label(t,text='BillID',bg='sky blue',font='bold ') 
   l1.place(x=100,y=50)   
   a=Entry(t,width=20)
   a.place(x=200,y=50)
   btf=Button(t,text='Find',command=finddata)
   btf.place(x=400,y=50)
   l2=Label(t,text='OrderId',bg='sky blue',font='bold ')
   l2.place(x=100,y=100)
   b=Entry(t,width=20)
   b.place(x=200,y=100)
   l3=Label(t,text='CustID',bg='sky blue',font='bold ')
   l3.place(x=100,y=150)
   c=Entry(t,width=20)
   c.place(x=200,y=150)
   l4=Label(t,text='Qty',bg='sky blue',font='bold ') 
   l4.place(x=100,y=200)   
   d=Entry(t,width=20)
   d.place(x=200,y=200)
   l5=Label(t,text='Price',bg='sky blue',font='bold ') 
   l5.place(x=100,y=250)   
   e=Entry(t,width=20)
   e.place(x=200,y=250)
   l6=Label(t,text='GST',bg='sky blue',font='bold ') 
   l6.place(x=100,y=300)   
   f=Entry(t,width=20)
   f.place(x=200,y=300)
   l7=Label(t,text='TotalBill',bg='sky blue',font='bold ') 
   l7.place(x=100,y=350)   
   g=Entry(t,width=20)
   g.place(x=200,y=350)
   t.config(bg='sky blue')

   t.mainloop()
    
def stockFind():
    t=tkinter.Tk()
    t.geometry('650x650')
    t.title('find data from stock')
    def finddata():
        db=pymysql.connect(host='localhost',
            user='root',password='Vkumar@1234',db='StockManagement')
        cur=db.cursor()
        p=(a.get())
        #placeholders %s string,%d int
        if len(p)==0:
            messagebox.showerror('Error','CANNOT FIND !')
        else:
            st="select Itemid,ItemCatID,DateIn,Qty from stock where Stockid='%s'"%(p)
            cur.execute(st)
            data=cur.fetchone()
            b.insert(0,data[0])
            c.insert(0,data[1])
            d.insert(0,data[2])
            e.insert(0,data[3])
            #save
            db.close()
    l1=Label(t,text='Stockid',bg='sky blue',font='bold ') 
    l1.place(x=100,y=50)   
    a=Entry(t,width=20)
    a.place(x=200,y=50)
    btf=Button(t,text='Find',command=finddata)
    btf.place(x=400,y=50)
    l2=Label(t,text='Itemid',bg='sky blue',font='bold ')
    l2.place(x=100,y=100)
    b=Entry(t,width=20)
    b.place(x=200,y=100)
    l3=Label(t,text='ItemCatID',bg='sky blue',font='bold ')
    l3.place(x=100,y=150)
    c=Entry(t,width=20)
    c.place(x=200,y=150)
    l4=Label(t,text='DateIn',bg='sky blue',font='bold ')
    l4.place(x=100,y=200)
    d=Entry(t,width=20)
    d.place(x=200,y=200)
    l5=Label(t,text='Qty',bg='sky blue',font='bold ')
    l5.place(x=100,y=250)
    e=Entry(t,width=20)
    e.place(x=200,y=250)
    t.config(bg='sky blue')

    t.mainloop()

def  itemcategoryUpdate():
    t=tkinter.Tk()
    t.geometry('650x650')
    t.title('Update data into itemcategory')
    def finddata():
        db=pymysql.connect(host='localhost',
            user='root',password='Vkumar@1234',db='StockManagement')
        cur=db.cursor()
        p=(a.get())
        #placeholders %s string,%d int
        if len(p)==0:
            messagebox.showerror('Error','CANNOT FIND ')
        else:
            st="select CatName,Description from itemcategory where ItemCatID='%s'"%(p)
            cur.execute(st)
            data=cur.fetchone()
            b.insert(0,data[0])
            c.insert(0,data[1])
            #save
            db.close()
    def updatedata():
        db=pymysql.connect(host='localhost',
            user='root',password='Vkumar@1234',db='StockManagement')
        cur=db.cursor()
        p=(a.get())
        q=b.get()
        r=c.get()
        #placeholders %s string,%d int
        st="update itemcategory set Catname='%s',Description='%s' where ItemCatID='%s'"%(q,r,p)
        cur.execute(st)
        db.commit()
        messagebox.showinfo('Update','Record Updated')
        #save
        db.close()
    a1=Label(t,text='ItemCatID')
    a1.place(x=100,y=50)
    a=Entry(t,width=20)
    a.place(x=300,y=50)
    btf=Button(t,text='Find',command=finddata)
    btf.place(x=500,y=50)
    b1=Label(t,text='CatName')
    b1.place(x=100,y=100)
    b=Entry(t,width=20)
    b.place(x=300,y=100)
    c1=Label(t,text='Description')
    c1.place(x=100,y=150)
    c=Entry(t,width=20)
    c.place(x=300,y=150)
    rr=Button(t,text='Update',command=updatedata)
    rr.place(x=300,y=350)
    t.config(bg='sky blue')
    t.mainloop()

def itemsUpdate():
    t=tkinter.Tk()
    t.geometry('650x650')
    t.title('Update data into items')
    def finddata():
        db=pymysql.connect(host='localhost',
            user='root',password='Vkumar@1234',db='StockManagement')
        cur=db.cursor()
        p=(a.get())
        #placeholders %s string,%d int
        if len(p)==0:
            messagebox.showerror('Error','CANNOT FIND ')
        else:
            st="select ItemCatID,IName,PricePerUnit,OpenQty,CurrentQty from items where Itemid='%s'"%(p)
            cur.execute(st)
            data=cur.fetchone()
            b.insert(0,data[0])
            c.insert(0,data[1])
            d.insert(0,data[2])
            e.insert(0,data[3])
            f.insert(0,data[4])
            #save
            db.close()
    def updatedata():
        db=pymysql.connect(host='localhost',
            user='root',password='Vkumar@1234',db='StockManagement')
        cur=db.cursor()
        p=(a.get())
        q=b.get()
        r=c.get()
        s=int(d.get())
        t=int(e.get())
        u=int(f.get())
        #placeholders %s string,%d int
        st="update items set ItemCatID='%s',IName='%s',PricePerUnit=%s,OpenQty=%s,CurrentQty=%s where Itemid='%s'"%(q,r,s,t,u,p)
        cur.execute(st)
        db.commit()
        messagebox.showinfo('Update','Record Updated')
        #save
        db.close()
    a1=Label(t,text='Itemid')
    a1.place(x=100,y=50)
    a=Entry(t,width=20)
    a.place(x=300,y=50)
    btf=Button(t,text='Find',command=finddata)
    btf.place(x=500,y=50)
    b1=Label(t,text='ItemCatID')
    b1.place(x=100,y=100)
    b=Entry(t,width=20)
    b.place(x=300,y=100)
    c1=Label(t,text='IName')
    c1.place(x=100,y=150)
    c=Entry(t,width=20)
    c.place(x=300,y=150)
    d1=Label(t,text='PricePerUnit')
    d1.place(x=100,y=200)
    d=Entry(t,width=20)
    d.place(x=300,y=200)
    e1=Label(t,text='OpenQty')
    e1.place(x=100,y=250)
    e=Entry(t,width=20)
    e.place(x=300,y=250)
    f1=Label(t,text='CurrentQty')
    f1.place(x=100,y=300)
    f=Entry(t,width=20)
    f.place(x=300,y=300)
    rr=Button(t,text='Update',command=updatedata)
    rr.place(x=300,y=350)
    t.config(bg='sky blue')
    t.mainloop()
    
def customerUpdate():
   t=tkinter.Tk()
   t.geometry('650x650')
   t.title('Update data into customer')
   def finddata():
       db=pymysql.connect(host='localhost',
           user='root',password='Vkumar@1234',db='StockManagement')
       cur=db.cursor()
       p=(a.get())
       #placeholders %s string,%d int
       if len(p)==0:
           messagebox.showerror('Error','CANNOT FIND ')
       else:
           st="select CName,Email,PhoneNo from customer where CustID='%s'"%(p)
           cur.execute(st)
           data=cur.fetchone()
           b.insert(0,data[0])
           c.insert(0,data[1])
           d.insert(0,data[2])
           #save
           db.close()
   def updatedata():
       db=pymysql.connect(host='localhost',
           user='root',password='Vkumar@1234',db='StockManagement')
       cur=db.cursor()
       p=(a.get())
       q=b.get()
       r=c.get()
       s=(d.get())
       #placeholders %s string,%d int
       st="update customer set CName='%s',Email='%s',PhoneNo='%s' where CustID='%s'"%(q,r,s,p)
       cur.execute(st)
       db.commit()
       messagebox.showinfo('Update','Record Updated')
       #save
       db.close()
   l1=Label(t,text='CustID',bg='sky blue',font='bold ') 
   l1.place(x=100,y=50)   
   a=Entry(t,width=20)
   a.place(x=200,y=50)
   btf=Button(t,text='Find',command=finddata)
   btf.place(x=400,y=50)
   l2=Label(t,text='CName',bg='sky blue',font='bold ')
   l2.place(x=100,y=100)
   b=Entry(t,width=20)
   b.place(x=200,y=100)
   l3=Label(t,text='Email',bg='sky blue',font='bold ')
   l3.place(x=100,y=150)
   c=Entry(t,width=20)
   c.place(x=200,y=150)
   l4=Label(t,text='PhoneNo',bg='sky blue',font='bold ')
   l4.place(x=100,y=200)
   d=Entry(t,width=20)
   d.place(x=200,y=200)
   rr=Button(t,text='Update',command=updatedata)
   rr.place(x=300,y=250)
   t.config(bg='sky blue')
   t.mainloop()
    
def orderUpdate():
     t=tkinter.Tk()
     t.geometry('650x650')
     t.title('Update data into orders')
     def finddata():
         db=pymysql.connect(host='localhost',
             user='root',password='Vkumar@1234',db='StockManagement')
         cur=db.cursor()
         p=(a.get())
         #placeholders %s string,%d int
         if len(p)==0:
             messagebox.showerror('Error','CANNOT FIND ')
         else:
             st="select CustId,OrdDate,ItemId,ItemCatID,Qty from orders where OrderID='%s'"%(p)
             cur.execute(st)
             data=cur.fetchone()
             b.insert(0,data[0])
             c.insert(0,data[1])
             d.insert(0,data[2])
             e.insert(0,data[3])
             f.insert(0,data[4])
             #save
             db.close()
     def updatedata():
         db=pymysql.connect(host='localhost',
             user='root',password='Vkumar@1234',db='StockManagement')
         cur=db.cursor()
         p=(a.get())
         q=b.get()
         r=c.get()
         s=(d.get())
         t=(e.get())
         u=int(f.get())
         #placeholders %s string,%d int
         st="update orders set CustID='%s',OrdDate='%s',ItemId='%s',ItemCatID='%s',Qty=%s where OrderID='%s'"%(q,r,s,t,u,p)
         cur.execute(st)
         db.commit()
         messagebox.showinfo('Update','Record Updated')
         #save
         db.close()
     a1=Label(t,text='OrderID')
     a1.place(x=100,y=50)
     a=Entry(t,width=20)
     a.place(x=300,y=50)
     btf=Button(t,text='Find',command=finddata)
     btf.place(x=500,y=50)
     b1=Label(t,text='CustID')
     b1.place(x=100,y=100)
     b=Entry(t,width=20)
     b.place(x=300,y=100)
     c1=Label(t,text='OrdDate')
     c1.place(x=100,y=150)
     c=Entry(t,width=20)
     c.place(x=300,y=150)
     d1=Label(t,text='ItemId')
     d1.place(x=100,y=200)
     d=Entry(t,width=20)
     d.place(x=300,y=200)
     e1=Label(t,text='ItemCatID')
     e1.place(x=100,y=250)
     e=Entry(t,width=20)
     e.place(x=300,y=250)
     f1=Label(t,text='Qty')
     f1.place(x=100,y=300)
     f=Entry(t,width=20)
     f.place(x=300,y=300)
     rr=Button(t,text='Update',command=updatedata)
     rr.place(x=300,y=350)
     t.config(bg='sky blue')
     t.mainloop()      
                                    
def billsUpdate():
     t=tkinter.Tk()
     t.geometry('650x650')
     t.title('Update data into bills')
     def finddata():
         db=pymysql.connect(host='localhost',
             user='root',password='Vkumar@1234',db='StockManagement')
         cur=db.cursor()
         p=(a.get())
         #placeholders %s string,%d int
         if len(p)==0:
             messagebox.showerror('Error','CANNOT FIND ')
         else:
             st="select OrderId,CustID,Qty,Price,GST,TotalBill from bills where BillID='%s'"%(p)
             cur.execute(st)
             data=cur.fetchone()
             b.insert(0,data[0])
             c.insert(0,data[1])
             d.insert(0,data[2])
             e.insert(0,data[3])
             f.insert(0,data[4])
             g.insert(0,data[5])
             #save
             db.close()
     def updatedata():
         db=pymysql.connect(host='localhost',
             user='root',password='Vkumar@1234',db='StockManagement')
         cur=db.cursor()
         p=(a.get())
         q=b.get()
         r=c.get()
         s=int(d.get())
         t=int(e.get())
         u=(f.get())
         v=int(g.get())
         #placeholders %s string,%d int
         st="update bills set OrderId='%s',CustID='%s',Qty=%s,Price=%d,GST='%s',TotalBill=%s where BillID='%s'"%(q,r,s,t,u,v,p)
         cur.execute(st)
         db.commit()
         messagebox.showinfo('Update','Record Updated')
         #save
         db.close()
     a1=Label(t,text='BillID')
     a1.place(x=100,y=50)
     a=Entry(t,width=20)
     a.place(x=300,y=50)
     btf=Button(t,text='Find',command=finddata)
     btf.place(x=500,y=50)
     b1=Label(t,text='OrderId')
     b1.place(x=100,y=100)
     b=Entry(t,width=20)
     b.place(x=300,y=100)
     c1=Label(t,text='CustID')
     c1.place(x=100,y=150)
     c=Entry(t,width=20)
     c.place(x=300,y=150)
     d1=Label(t,text='Qty')
     d1.place(x=100,y=200)
     d=Entry(t,width=20)
     d.place(x=300,y=200)
     e1=Label(t,text='Price')
     e1.place(x=100,y=250)
     e=Entry(t,width=20)
     e.place(x=300,y=250)
     f1=Label(t,text='GST')
     f1.place(x=100,y=300)
     f=Entry(t,width=20)
     f.place(x=300,y=300)
     g1=Label(t,text='TotalBill')
     g1.place(x=100,y=350)
     g=Entry(t,width=20)
     g.place(x=300,y=350)
     rr=Button(t,text='Update',command=updatedata)
     rr.place(x=350,y=450)
     t.config(bg='sky blue')
     t.mainloop()                                                                              
                                                
def stockUpdate():
     t=tkinter.Tk()
     t.geometry('650x650')
     t.title('Update data into stock')
     def finddata():
         db=pymysql.connect(host='localhost',
             user='root',password='Vkumar@1234',db='StockManagement')
         cur=db.cursor()
         p=(a.get())
         #placeholders %s string,%d int
         if len(p)==0:
             messagebox.showerror('Error','CANNOT FIND ')
         else:
             st="select ItemId,ItemCatID,DateIn,Qty from stock where Stockid='%s'"%(p)
             cur.execute(st)
             data=cur.fetchone()
             b.insert(0,data[0])
             c.insert(0,data[1])
             d.insert(0,data[2])
             e.insert(0,data[3])
             #save
             db.close()
     def updatedata():
         db=pymysql.connect(host='localhost',
             user='root',password='Vkumar@1234',db='StockManagement')
         cur=db.cursor()
         p=(a.get())
         q=b.get()
         r=c.get()
         s=(d.get())
         t=int(e.get())
         #placeholders %s string,%d int
         st="update stock set ItemId='%s',ItemCatID='%s',DateIn='%s',Qty=%s where Stockid='%s'"%(q,r,s,t,p)
         cur.execute(st)
         db.commit()
         messagebox.showinfo('Update','Record Updated')
         #save
         db.close()
     a1=Label(t,text='Stockid')
     a1.place(x=100,y=50)
     a=Entry(t,width=20)
     a.place(x=300,y=50)
     btf=Button(t,text='Find',command=finddata)
     btf.place(x=500,y=50)
     b1=Label(t,text='Itemid')
     b1.place(x=100,y=100)
     b=Entry(t,width=20)
     b.place(x=300,y=100)
     c1=Label(t,text='ItemCatID')
     c1.place(x=100,y=150)
     c=Entry(t,width=20)
     c.place(x=300,y=150)
     d1=Label(t,text='DateIn')
     d1.place(x=100,y=200)
     d=Entry(t,width=20)
     d.place(x=300,y=200)
     e1=Label(t,text='Qty')
     e1.place(x=100,y=250)
     e=Entry(t,width=20)
     e.place(x=300,y=250)
     rr=Button(t,text='Update',command=updatedata)
     rr.place(x=300,y=350)
     t.config(bg='sky blue')
     t.mainloop()

def itemcategoryDelete():
    t=tkinter.Tk()
    t.geometry('650x650')
    t.title('Delete data from itemcategory')
    def deletedata():
        db=pymysql.connect(host='localhost',
            user='root',password='Vkumar@1234',db='StockManagement')
        cur=db.cursor()
        p=a.get()
        if len(p)==0:
            messagebox.showerror('Error','CANNOT DELETED')
        else:
            st="delete from  itemcategory where ItemCatID='%s'"%(p)
            cur.execute(st)
            messagebox.showinfo('Data Deleted','Deleted')
            #save
            db.commit()
            db.close()
            a.delete(0,100)
    l=Label(t,text="ItemCatID")
    l.place(x=100,y=50)    
    a=Entry(t,width=20)
    a.place(x=200,y=50)
    bt=Button(t,text='Save',command=deletedata)
    bt.place(x=200,y=300)
    t.config(bg='sky blue')
    t.mainloop()

def itemsDelete():
    t=tkinter.Tk()
    t.geometry('650x650')
    t.title('Delete data from items')
    def deletedata():
        db=pymysql.connect(host='localhost',
            user='root',password='Vkumar@1234',db='StockManagement')
        cur=db.cursor()
        p=a.get()
        if len(p)==0:
            messagebox.showerror('Error','Cannot Delete')
        else:
            st="delete from  items where Itemid='%s'"%(p)
            cur.execute(st)
            messagebox.showinfo('Data Deleted','Deleted')
            #save
            db.commit()
            db.close()
            a.delete(0,100)
    l=Label(t,text="ItemCatID")
    l.place(x=100,y=50)    
    a=Entry(t,width=20)
    a.place(x=200,y=50)
    bt=Button(t,text='Save',command=deletedata)
    bt.place(x=200,y=300)
    t.config(bg='sky blue')
    t.mainloop()
  

def customerDelete():
   t=tkinter.Tk()
   t.geometry('650x650')
   t.title('Delete data from customer')
   def deletedata():
       db=pymysql.connect(host='localhost',
           user='root',password='Vkumar@1234',db='StockManagement')
       cur=db.cursor()
       p=a.get()
       if len(p)==0:
           messagebox.showerror('Error','Cannot Delete')
       else:
           st="delete from customer where CName='%s'"%(p)
           cur.execute(st)
           messagebox.showinfo('Data Deleted','Deleted')
           #save
           db.commit()
           db.close()
           a.delete(0,100)
   l=Label(t,text="CName")
   l.place(x=100,y=50)    
   a=Entry(t,width=20)
   a.place(x=200,y=50)
   bt=Button(t,text='Save',command=deletedata)
   bt.place(x=200,y=300)
   t.config(bg='sky blue')
   t.mainloop()  

def ordersDelete():
    t=tkinter.Tk()
    t.geometry('650x650')
    t.title('Delete data from orders')
    def deletedata():
        db=pymysql.connect(host='localhost',
            user='root',password='Vkumar@1234',db='StockManagement')
        cur=db.cursor()
        p=a.get()
        if len(p)==0:
            messagebox.showerror('Error','Cannot Delete')
        else:
            st="delete from orders where OrderID='%s'"%(p)
            cur.execute(st)
            messagebox.showinfo('Data Deleted','Deleted')
            #save
            db.commit()
            db.close()
            a.delete(0,100)
    l=Label(t,text="OrderID")
    l.place(x=100,y=50)    
    a=Entry(t,width=20)
    a.place(x=200,y=50)
    bt=Button(t,text='Save',command=deletedata)
    bt.place(x=200,y=300)
    t.config(bg='sky blue')
    t.mainloop()                                                       
                                                           
def stockDelete():
    t=tkinter.Tk()
    t.geometry('650x650')
    t.title('Delete data from stock')
    def deletedata():
        db=pymysql.connect(host='localhost',
            user='root',password='Vkumar@1234',db='StockManagement')
        cur=db.cursor()
        p=a.get()
        if len(p)==0:
            messagebox.showerror('Error','Cannot Delete')
        else:
            st="delete from stock where Stockid='%s'"%(p)
            cur.execute(st)
            messagebox.showinfo('Data Deleted','Deleted')
            #save
            db.commit()
            db.close()
            a.delete(0,100)
       
    l=Label(t,text="Stockid")
    l.place(x=100,y=50)    
    a=Entry(t,width=20)
    a.place(x=200,y=50)
    bt=Button(t,text='Save',command=deletedata)
    bt.place(x=200,y=300)
    t.config(bg='sky blue')
    t.mainloop()
    
def billsDelete():
        t=tkinter.Tk()
        t.geometry('650x650')
        t.title('Delete data from bills')
        def deletedata():
            db=pymysql.connect(host='localhost',
                user='root',password='Vkumar@1234',db='StockManagement')
            cur=db.cursor()
            p=a.get()
            if len(p)==0:
                messagebox.showerror('Error','Cannot Delete')
            else:
                st="delete from  bills where  BillID='%s'"%(p)
                cur.execute(st)
                messagebox.showinfo('Data Deleted','Deleted')
                #save
                db.commit()
                db.close()
                a.delete(0,100)
            
        l=Label(t,text="BillID")
        l.place(x=100,y=50)    
        a=Entry(t,width=20)
        a.place(x=200,y=50)
        bt=Button(t,text='Save',command=deletedata)
        bt.place(x=200,y=300)
        t.config(bg='sky blue')
        t.mainloop()                                                         